/**
 * A tool call from the MCP bridge, addressed at a specific pane.
 *
 * `id` is chosen by the caller and echoed back on the matching
 * `McpResponse` so a bridge juggling more than one in-flight call can tell
 * its answers apart.
 */
export interface McpRequest {
  id: number
  paneId: string
  tool: string
  args: Record<string, unknown>
}

/**
 * The answer to one `McpRequest`, carrying the same `id`.
 *
 * Unlike a hook line, a request always gets a response: the bridge is
 * waiting on this `id` and has no other way to learn the call failed.
 */
export type McpResponse = { id: number; ok: true; result: unknown } | { id: number; ok: false; error: string }

/**
 * Sized for what this plan actually sends: a `browser_navigate` request
 * whose payload is one URL. 2048 characters is the long-standing de facto
 * safe maximum for a URL (originally Internet Explorer's limit, still the
 * number most commonly cited for cross-tool compatibility), and the JSON
 * wrapper around it (`id`, `paneId`, `tool`, the `args` object, plus
 * escaping) adds at most a few hundred bytes on top. 8192 is four times
 * that combined size, comfortably larger than any real navigate line while
 * still refusing a runaway line before it becomes an unbounded allocation.
 * It is larger than the hooks' 512 because a URL is a bigger payload than a
 * hook event.
 *
 * Responses are generated by this app, not parsed by it, so they have no
 * cap here.
 */
export const MAX_LINE_BYTES = 8192

/**
 * Read one request line sent to the socket, or return null.
 *
 * Never throws. This is the bridge's only untrusted input, so it refuses
 * everything it does not positively recognise rather than accepting
 * everything it cannot disprove. Unlike `parseHookLine`, a null here is not
 * the end of it: the caller still owes the bridge a response, because
 * there is no other way for a waiting `id` to learn its call failed. This
 * function cannot supply that id itself (a line that fails to parse may
 * not even have one), so producing the "malformed request" response is the
 * caller's job.
 */
export function parseRequestLine(line: string): McpRequest | null {
  if (Buffer.byteLength(line, 'utf8') > MAX_LINE_BYTES) return null
  const trimmed = line.trim()
  if (trimmed.length === 0) return null

  let value: unknown
  try {
    value = JSON.parse(trimmed)
  } catch {
    return null
  }
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return null

  const candidate = value as {
    id?: unknown
    paneId?: unknown
    tool?: unknown
    args?: unknown
  }

  if (typeof candidate.id !== 'number' || !Number.isFinite(candidate.id)) return null
  if (typeof candidate.paneId !== 'string') return null
  if (typeof candidate.tool !== 'string') return null

  let args: Record<string, unknown> = {}
  if (candidate.args !== undefined) {
    if (typeof candidate.args !== 'object' || candidate.args === null || Array.isArray(candidate.args)) return null
    args = candidate.args as Record<string, unknown>
  }

  return { id: candidate.id, paneId: candidate.paneId, tool: candidate.tool, args }
}

/**
 * Write one response line to send back over the socket.
 *
 * `JSON.stringify` escapes any newline inside `error` (or anywhere else in
 * the response) as the two characters `\n`, not a real line break, so the
 * single `\n` appended here is the only one in the returned string. That
 * is what keeps a free-text error message from forging a second line the
 * bridge would try to parse as its own response.
 */
export function formatResponseLine(response: McpResponse): string {
  return `${JSON.stringify(response)}\n`
}
